---
title: "Untitled"
format: html
editor: visual
---

```{r}
# load libraries
library(tidyverse)
library(lubridate)
library(stringr)

# load sample
data = read_csv("AHS_full_data.csv")
```

```{r}
# filter sample to renters & respondents
sample = data |>
  filter(INTSTATUS == 1 # occupied household
         & RESPONDENT == 1  # only respondents
         & is.na(MOVERGRP) == F # just new mover group
         & TENURE == 2) # only renters
```

```{r}
# variable recoding
sample = sample |>
  mutate(citizen = case_match(CITSHP, 
                              c(1,2,3,4) ~ 0, # is not U.S citizen
                              c(5) ~ 1), # is U.S. citizen
         age = AGE,
         
         family_relationship = case_match(FAMREL, 
                                          0 ~ "(1) not in family",
                                          1 ~ "(2) reference person of family",
                                          2 ~ "(3) spouse of reference person of family",
                                          3 ~ "(4) other relative of reference person o family"),
         ed_level = case_match(GRAD,
                               31:38 ~ "(1) less than highschool diploma",
                               39 ~ "(2) highschool diploma",
                               40:43 ~ "(3) some post-secondary education",
                               44 ~ "(4) bachelor's degree",
                               44:47 ~ "(5) greater than bachelor's degree"),
         marital_status = case_match(MAR,
                                     c(1,2) ~ "(1) married",
                                     c(3,4,5) ~ "(2) previously married",
                                     6 ~ "(3) never married"),
         military_status = case_match(MIL,
                                      1 ~ "(1) current military",
                                      2 ~ "(2) previous military",
                                      3 ~ "(3) never military"),
         race = case_match(RACE,
                            1 ~ "(1) white only",
                            2 ~ "(2) black only",
                            3 ~ "(3) Indigenous American",
                            c(4,5) ~ "(4) Asian or Pacific Islander",
                            6:21 ~ "(5) More than one race"),
         sex = case_match(SEX, 
                          1 ~ "male", 
                          2 ~ "female"),
         hispanic = case_match(SPAN,
                              1 ~ 1,
                              2 ~ 0),
         building_type = case_match(BLD,
           c(1,10) ~ "mobile home, trailer, boat, van, etc.",
           2 ~ "one-family house detached",
           3 ~ "one-family house attached",
           c(4,5,6) ~ "2 to 9 apartments",
           c(7,8) ~ "10 to 49 apartments",
           9 ~ "50 more more apartments"
         ),
         unit_size = case_match(UNITSIZE,
                                1:2 ~ "(1) less than 750 sq. feet",
                                3 ~ "(2) 750 - 999 sq. feet",
                                4 ~ "(3) 1,00 - 1,499 sq. feet",
                                5 ~ "(4) 1,500 - 1,999 sq. feet",
                                6:9 ~ "(5) more than 2,000 sq. feet"),
         bedroooms = BEDROOMS,
         bathrooms = BATHROOMS,
         washer = WASHER,
         mold_bedroom = case_match(MOLDBEDRM,
                                   1 ~ 1,
                                   2 ~ 0),
         mold_kitchen = case_match(MOLDKITCH,
                                   1 ~ 1,
                                   2 ~ 0),
         mold_room = case_match(MOLDLROOM,
                                1 ~ 1,
                                2 ~ 0),
         mold_index = mold_bedroom + mold_room + mold_kitchen, # left out mold in bathroom because that is pretty normal
         roach_weekly = case_match(ROACH,
                                   1:2 ~ 1,
                                   3:5 ~ 0),
         roach_daily = case_match(ROACH, 
                                  1 ~ 1,
                                  2:5 ~ 0),
         wall_crack = case_match(WALLCRACK,
                                 1 ~ 1,
                                 2 ~ 0),
         household_type = case_match(HSHLDTYPE,
                                     1 ~ "(1) Married-couple family houshold",
                                     2:3 ~ "(2) Other family household",
                                     4:7 ~ "(3) Nonfamily household"),
         multi_gen = case_match(MULTIGEN,
                                1 ~ " (1) householder only",
                                2:3 ~ "(2) Householder and younger generation",
                                4 ~ "(3) Housholder and younger and older generation",
                                5:6 ~ "(4) Householder and older generation"),
         num_ppl = NUMPEOPLE,
         same_household = case_match(SAMEHHLD,
                                     1 ~ "all household members same",
                                     2:4 ~ "at least some household members different"),
         # hh_ means house-holder
         hh_citizen = case_match(HHCITSHP, 
                              c(1,2,3,4) ~ 0, 
                              c(5) ~ 1),
         hh_age = HHAGE,
         hh_ed_level = case_match(HHGRAD,
                              31:38 ~ "(1) less than highschool diploma",
                               39 ~ "(2) highschool diploma",
                               40:43 ~ "(3) some post-secondary education",
                               44 ~ "(4) bachelor's degree",
                               44:47 ~ "(5) greater than bachelor's degree"),
         hh_mar = case_match(HHMAR,
                                     c(1,2) ~ "(1) married",
                                     c(3,4,5) ~ "(2) previously married",
                                     6 ~ "(3) never married"),
         hh_military_status = case_match(MILHH,
                                      1 ~ "(1) current military",
                                      2 ~ "(2) previous military",
                                      3 ~ "(3) never military"),
         hh_race = case_match(HHRACE,
                            1 ~ "(1) white only",
                            2 ~ "(2) black only",
                            3 ~ "(3) Indigenous American",
                            c(4,5) ~ "(4) Asian or Pacific Islander",
                            6:21 ~ "(5) More than one race"),
         hh_sex = case_match(HHSEX, 
                          1 ~ "male", 
                          2 ~ "female"),
         hh_hispanic = case_match(HHSPAN,
                              1 ~ 1,
                              2 ~ 0),
         family_income = FINCP,
         rent = RENT,
         total_housing_costs = TOTHCAMT,
         hud_assist =  case_match(HUDSUB,
                                  3 ~ "(1) Non-HUD assisted",
                                  1 ~ "(2) HUD assisted public housing",
                                  2 ~ "(3) HUD assited voucher"),
         near_aband = case_match(NEARABAND,
                                 c(3,4) ~ 0, # no vandalized or abandoned buildings
                                 1 ~ 1, # not more than 1 vand or abandoned building
                                 2 ~ 2), # more than 1
         near_trash = case_match(NEARTRASH,
                                 3 ~ 0, # 3: No trash
                                 2 ~ 1, # 2: Small amount of trash
                                 1 ~ 2), # Large amount of trash
         near_bars = case_match(NEARBARCL,
                                3 ~ 0,  # No buildings with metal bars
                                1 ~ 1, #  Not more than one building with metal bars
                                2 ~ 2), # More than one building with metal bars
         # create neighborhood neglect index
         neighborhood_index = near_aband + near_trash + near_bars,
         neighborhood_rating = RATINGNH,
         unit_rating = RATINGHS,
         personalnet_search = case_match(SEARCHFAM,
                                      1 ~ 1,
                                      2 ~ 0),
         internet_search = case_match(SEARCHNET,
                                      1 ~ 1,
                                      2 ~ 0),
         apt_listing_search = case_match(SEARCHLIST,
                                         1 ~ 1,
                                         2 ~ 0),
         move_force = case_match(MOVFORCE,
                                 1 ~ 1,
                                 2 ~ 0),
         move_hhchange = case_match(RMCHANGE,
                                    1 ~ 1,
                                    2 ~ 0),
         move_commute = case_match(RMCOMMUTE,
                                   1 ~ 1,
                                  2 ~ 0),
         move_cost = case_match(RMCOSTS,
                                1 ~ 1,
                                2 ~ 0),
         move_family = case_match(RMFAMILY,
                                  1 ~ 1,
                                  2 ~ 0),
         move_upgrade_h = case_match(RMHOME,
                                   1 ~ 1,
                                   2 ~ 0),
         move_upgrade_nh = case_match(RMHOOD,
                                      1 ~ 1,
                                      2 ~ 0),
         move_job = case_match(RMJOB,
                                      1 ~ 1,
                                      2 ~ 0),
         move_other = case_match(RMOTHER,
                                      1 ~ 1,
                                      2 ~ 0),
         move_formhh = case_match(RMOWNHH,
                                      1 ~ 1,
                                      2 ~ 0),
         year_move = MOVE
         )

# merge geographic info
metro_codes = read_csv("metro_codes.csv")
head(metro_codes)

# extra code and metro name
metro_codes$OMB13CBSA = str_match(metro_codes$codes, "^[:whitespace:]*([:digit:]+)")[,1]
metro_codes$cbsa = str_match(metro_codes$codes, '^[:whitespace:]*([:digit:]+)," (.*)"')[,3]
metro_codes$state = str_match(metro_codes$codes, '([-,[:alpha:]]+)"$')

# get rid of extra column
metro_codes = metro_codes[, c(2,3)]

# merge with sample
sample$OMB13CBSA = as.character(sample$OMB13CBSA) # change metro indicator in sample to character
sample = left_join(sample, metro_codes, by = "OMB13CBSA")

```

```{r}
# subset sample to just cleaned/recoded columns
sample = sample |>
  select(1,13, 83:141)

# add extra family_income recode
sample = sample |>
  mutate(family_income1000 = family_income/1000)

# show cleaned data
head(sample)
```

```{r}
# create analytic sample (base on control variables and outcome variables used in model)
analytic_sample = sample |>
  filter(is.na(personalnet_search) == F & 
           is.na(unit_rating) == F &
           is.na(neighborhood_rating) == F &
           is.na(neighborhood_index) == F &
           is.na(wall_crack) == F &
           is.na(race) == F &
           is.na(hispanic) == F &
           is.na(ed_level) == F &
           is.na(family_income1000) == F &
           is.na(move_force) == F &
           is.na(total_housing_costs) == F &
           is.na(household_type) == F &
           is.na(multi_gen) == F &
           is.na(num_ppl) == F &
           is.na(age) == F &
           is.na(race) == F &
           is.na(sex) == F &
           is.na(marital_status) == F &
           is.na(military_status) == F &
           is.na(citizen) == F &
           is.na(family_relationship) == F &
           is.na(same_household) == F &
           is.na(cbsa) == F &
           is.na(year_move) == F)

```

```{r}
# descriptive statistic graphing

# used outside resources to learn about these packages for plotting more than one figure together
library(gridExtra)
library(patchwork)

# sources for learning about package
## gridExtra: https://www.geeksforgeeks.org/r-language/saving-gridarrange-plot-to-file-in-r/
## patckwork: https://patchwork.data-imaginist.com/

# ai disclosure: I used ai (google search gemini pop-up) to remind myself and learn about certain ggplot options

# descriptive stats visualization - racial differences in housing outcomes

# housing unit rating plot
h_rate = analytic_sample |>
  group_by(race) |>
  summarise(avg_rating = mean(unit_rating))

hrate_plot = ggplot(h_rate,aes (x =race, y = avg_rating, fill = race)) +
  geom_bar(stat = "identity", position = "dodge") + guides(fill = "none") +
  theme(axis.text.x = element_blank(), plot.title = element_text(size = 10)) + 
  ggtitle("Average Housing Unit Rating (1 - 10)")

# neighborhood rating plot
nh_rate = analytic_sample |>
  group_by(race) |>
  summarise(avg_rating = mean(neighborhood_rating))

nhrate_plot = ggplot(nh_rate,aes (x =race, y = avg_rating, fill = race)) +
  geom_bar(stat = "identity", position = "dodge") + 
  theme(axis.text.x = element_blank(), plot.title = element_text(size = 10)) +
  ggtitle("Average Neighborhood Unit Rating (1-10)")

# combine plots together
combined = hrate_plot + nhrate_plot
combined

# wall crack
wallcrack = analytic_sample |>
  group_by(race) |>
  summarise(wallcrack_pct = mean(wall_crack))

wc_plot = ggplot(wallcrack,aes (x =race, y = wallcrack_pct, fill = race)) +
  geom_bar(stat = "identity", position = "dodge") + guides(fill = "none") +
   ggtitle("Presence of Wall Cracks In Unit (%)") +
  theme(axis.text.x = element_blank(), plot.title = element_text(size = 10))

# neighborhood disinvestment index 
nhind = analytic_sample |>
  group_by(race) |>
  summarise(avg_score = mean(neighborhood_index))

nhind_plot = ggplot(nhind,aes (x =race, y = avg_score, fill = race)) +
  geom_bar(stat = "identity", position = "dodge") + guides(fill = "none") +
  theme(axis.text.x = element_blank(), plot.title = element_text(size = 8)) +
  ggtitle("Averaage Neighborhood Disinvestment Score (0 - 6)")

# combine plots together
grid.arrange(wc_plot, nhind_plot, ncol = 2)


```


```{r}
# plot use of personal networks throughout move years
networks = analytic_sample |>
  group_by(year_move) |>
  summarise(personal_network_pct = mean(personalnet_search)*100)

ggplot(networks) + 
  geom_line(aes(x = year_move, y = personal_network_pct))

```

```{r}
# show racial distribution of sample
library(gtsummary)
# source: https://www.danieldsjoberg.com/gtsummary/

# make table
t1 = tbl_summary(analytic_sample, include = race)

# export table
t1 |>
  as_gt() |> 
  gt::gtsave(filename = "racial_dem.docx")
```

```{r}

# subjective rating of unit quality while controlling for rent and demographic factors. 1 - 10 scale
place_rating_model_1 = lm(unit_rating ~ personalnet_search*race, data = analytic_sample)
place_rating_model_2 = lm(unit_rating ~ personalnet_search*race + hispanic + ed_level + family_income1000 + move_force + total_housing_costs + household_type + multi_gen + num_ppl + age + sex + marital_status + military_status + citizen + family_relationship + same_household + cbsa + factor(year_move), data = analytic_sample)

## create tables
t1 = tbl_regression(place_rating_model_1) |> add_n()
t2 = tbl_regression(place_rating_model_2) |> add_n()

## merge tables together 
tbl_merge <-
  tbl_merge(
    tbls = list(t1, t2),
    tab_spanner = c("**Unit Rating (Model 1)**", "**Unit Rating (Model 2)**")
  )

## export table
tbl_merge |> 
  as_gt() |> 
  gt::gtsave(filename = "subjective_outcomes_unit.docx")

## subjective rating of neighborhood quality
nh_rating_model_1 = lm(neighborhood_rating ~ personalnet_search*race, data = analytic_sample)
nh_rating_model_2 = lm(neighborhood_rating ~ personalnet_search*race + hispanic + ed_level + family_income1000 + move_force + total_housing_costs + household_type + multi_gen + num_ppl + age + sex + marital_status + military_status + citizen + family_relationship + same_household + cbsa + factor(year_move), data = analytic_sample)

## create tables
t3 = tbl_regression(nh_rating_model_1) |> add_n()
t4 = tbl_regression(nh_rating_model_2) |> add_n()

## merge tables together 
tbl_merge <-
  tbl_merge(
    tbls = list(t3, t4),
    tab_spanner = c("**Neighborhood Rating (Model 1)**", "**Neighborhood Rating (Model 2)**")
  )

# export subjective outcomes for neighborhood
## export table
tbl_merge |> 
  as_gt() |> 
  gt::gtsave(filename = "subjective_outcomes_neighborhood.docx")

```

```{r}
# OBJECTIVE MEASURES

# crack in wall logistic regression
wall_crack_model_1 = glm(wall_crack ~ personalnet_search*race, family = binomial, data = analytic_sample)
summary(wall_crack_model_1)

wall_crack_model_2 = glm(wall_crack ~ personalnet_search*race + hispanic + ed_level + family_income1000 + move_force + total_housing_costs + household_type + multi_gen + num_ppl + age + sex + marital_status + military_status + citizen + family_relationship + same_household + cbsa + factor(year_move), family = binomial, data = analytic_sample)

# make table
t1 = tbl_regression(wall_crack_model_1, exponentiate = TRUE)
t2 = tbl_regression(wall_crack_model_2, exponentiate = TRUE)

# export table
## merge tables together 
tbl_merge <-
  tbl_merge(
    tbls = list(t1, t2),
    tab_spanner = c("**Crack in Wall (Model 1)**", "** Crack in Wall (Model 2)**")
  )

## export table
tbl_merge |> 
  as_gt() |> 
  gt::gtsave(filename = "objective_outcomes_unit.docx")

# Neighborhood disinvestment index

## build model
neighborhood_index_1 = lm(neighborhood_index ~ personalnet_search*race, data = analytic_sample)

neighborhood_index_2 = lm(neighborhood_index ~ personalnet_search*race + hispanic + ed_level + family_income1000 + move_force + total_housing_costs + household_type + multi_gen + num_ppl + age + sex + marital_status + military_status + citizen + family_relationship + same_household + cbsa + factor(year_move), data = analytic_sample)

# make table
t3 = tbl_regression(neighborhood_index_1)
t4 = tbl_regression(neighborhood_index_2)

## merge tables together 
tbl_merge <-
  tbl_merge(
    tbls = list(t3, t4),
    tab_spanner = c("** Neighborhood Disinvestment Index (Model 1)**", "** Neighborhood Disinvestment Index (Model 2)**")
  )
## export table
tbl_merge |> 
  as_gt() |> 
  gt::gtsave(filename = "objective_outcomes_neighborhood.docx")

```
